/* ============================================================================
   gantt-data.js · DATI del Gantt Santamonica  (renderer: GANTT_Santamonica.html)
   ----------------------------------------------------------------------------
   FILE GENERATO — non modificare a mano.
   Fonte: note Obsidian in Jarvis/Task/ → node Jarvis/_tools/jarvis.mjs build-gantt
   ============================================================================ */
window.SANTAMONICA_GANTT = {
  version: "2026.09.25.11",
  updated: "2026-09-25",
  axisStart: "2026-05-01",
  axisEnd:   "2027-09-01",
  today:     "2026-09-25",

  sections: [
    { key:'dec', name:'★ Decennale — serata 1 luglio 2026', badge:'evento trasversale', tasks:[
      {t:'Concept decennale chiuso', s:'2026-05-28', st:'done', ms:true},
      {t:'Funnel comunicazione W1–W5', s:'2026-05-27', e:'2026-07-01', st:'done'},
      {t:'Sessione foto (genero)', s:'2026-06-01', e:'2026-06-07', st:'done'},
      {t:'Bloccanti chiusi (musicista · Muratori · brief Nicolò · invitati)', s:'2026-06-02', e:'2026-06-05', st:'done'},
      {t:'Teaser organici (~2/sett, crescendo)', s:'2026-06-04', e:'2026-07-01', st:'done'},
      {t:'Gate boost decennale: creatività + copy + landing allineati', s:'2026-06-04', e:'2026-06-16', st:'done'},
      {t:'Apertura prenotazioni pubbliche', s:'2026-06-12', e:'2026-06-30', st:'done'},
      {t:'Reel 2016→2026: brief + scaletta foto per Monica', s:'2026-06-16', st:'done', ms:true},
      {t:'Boost Reel decennale LIVE (via advertiser "Ristorante Santamonica", end date)', s:'2026-06-16', e:'2026-06-28', st:'done'},
      {t:'Account Meta 264 SBLOCCATO (verificato dal vivo 29/6) — config business "1" resta aperta', s:'2026-06-16', e:'2026-06-29', st:'done', ms:true},
      {t:'SERATA DECENNALE (56/60 ospiti, 10 dal canale pubblico)', s:'2026-07-01', st:'done', ms:true},
    ]},
    { key:'sito', name:'Sito (SantaWeb + SafeTable)', badge:'progetto-sito', tasks:[
      {t:'Go-live sito Cloudflare Pages', s:'2026-05-22', st:'done', ms:true},
      {t:'GA4 + Meta Pixel attivi', s:'2026-05-27', st:'done', ms:true},
      {t:'Carta-garanzia prenotazioni — Fase 1 LIVE', s:'2026-05-27', e:'2026-05-28', st:'done'},
      {t:'Prenotazioni: blocco / aperture / singoli orari', s:'2026-05-30', st:'done', ms:true},
      {t:'Fix mobile r-mail.html', s:'2026-05-30', e:'2026-06-01', st:'done'},
      {t:'Cambio orari (dal 7/6)', s:'2026-06-05', e:'2026-06-07', st:'done'},
      {t:'Orario estivo (cena 20:00–22:30, mar–dom · pranzo chiuso · 21/6→31/8; ripristino da 1/9)', s:'2026-06-21', e:'2026-08-31', st:'done'},
      {t:'menu-admin CSP + QR + controlli stampa', s:'2026-06-10', st:'done'},
      {t:'Sicurezza cauzioni RLS chiusa', s:'2026-06-11', st:'done', ms:true},
      {t:'Fix M1: ricevuta non conferma (v21)', s:'2026-06-12', st:'done', ms:true},
      {t:'newsletter-confermata.html + DOI redirect (v22)', s:'2026-06-12', st:'done', ms:true},
      {t:'Ramo Voucher — acquisto automatico Stripe live (PDF+mail), IVA confermata commercialista (14/7)', s:'2026-06-10', e:'2026-07-20', st:'done', ms:true},
      {t:'Voucher — fase di test completata: rate limit ripristinato 5/ora, CTA home→/regala.html, testo validità/uso allineato ovunque (sito+PDF+termini+admin)', s:'2026-07-21', st:'done', ms:true},
      {t:'Voucher — P3 pacchetto completo SALTATA su decisione esplicita Andrea (21/7) = debito dichiarato, non bloccante', s:'2026-07-21', st:'done', ms:true},
      {t:'Landing /decennale (3 partner: Muratori · Cà du Ferrà · Pascucci)', s:'2026-06-08', e:'2026-06-13', st:'done', ms:true},
      {t:'Landing /10anni: CTA telefono/DM + allineamento (v.16.03)', s:'2026-06-21', st:'done'},
      {t:'Reminder automatico prenotazioni (pannello + pg_cron, gate P3 debito)', s:'2026-07-04', st:'done', ms:true},
      {t:'Gestionale prenotazioni — Fase 1 Calendario/Servizio (ispirato TheFork Manager)', s:'2026-07-05', st:'done', ms:true},
      {t:'Gestionale — stato Arrivato/No-show manuale + Garanzia richiesta/effettuata (da SafeTable)', s:'2026-07-05', st:'done', ms:true},
      {t:'Reminder — passato da "solo confermate" ad automatico per tutte le prenotazioni future (da mar 7/7/2026)', s:'2026-07-05', st:'done', ms:true},
      {t:'No-show → sync SafeTable/cauzioni (no_show_at) + reminder panel "solo da domani"', s:'2026-07-05', st:'done', ms:true},
      {t:'"Arrivato" → sync SafeTable/cauzioni (status=arrived, disabilita $ penale)', s:'2026-07-05', st:'done', ms:true},
      {t:'Incidente: STRIPE_SECRET_KEY invalida (mk_...) bloccava TUTTI i pagamenti live (voucher+cauzioni) — trovato e risolto in sessione', s:'2026-07-23', st:'done', ms:true},
      {t:'Wizard prenotazioni /prenota.html — carta a garanzia SEMPRE obbligatoria + conferma AUTOMATICA (no revisione manuale); gate chiuso, P3 saltata=debito, test e2e OK', s:'2026-07-23', st:'done', ms:true},
      {t:'Limiti posti per fascia oraria visibili nel gestionale (gestionale-day v3 + chip prenotati/liberi) + fix testo fuorviante limiti', s:'2026-07-25', st:'done', ms:true},
      {t:'Refactor orari "PERIODS" — prenotazioni future (settembre/ottobre) già corrette da oggi, non solo a cambio orario avvenuto (fix bug scoperto da Andrea) + fix 4° mirror gestionale-calendar-status', s:'2026-07-25', st:'done', ms:true},
      {t:'Setup penale/ore-disdetta garanzia configurabili (menu-admin) — sostituiscono i 25€/24h fissi ovunque; scoperto card_required_days=[] da chiarire con Andrea', s:'2026-07-25', st:'done', ms:true},
      {t:'No-show gestionale → sync automatico con storico "pacchi" NoShowApp (nuovo ponte noshow-pacchi-bridge)', s:'2026-07-26', st:'done', ms:true},
      {t:'Pannello "Pacchi No-show" in sola lettura in menu-admin (elenco pacchi da NoShowApp)', s:'2026-07-26', st:'done', ms:true},
      {t:'Cliente segnalato (pacchi No-show) in mail M1bis + gestionale (nome rosso→arancione dopo redenzione)', s:'2026-07-27', st:'done', ms:true},
      {t:'Ripristino orari pre-estivi dal 1/9 (contenuti statici JSON-LD/FAQ aggiornati dal task schedulato 28/8; foglio stampa menu.html/menu-it.html già corretto sul live; disponibilità prenotazioni già corretta da prima)', s:'2026-08-28', e:'2026-09-01', st:'done', ms:true},
      {t:'Chiusura cena domenica dal 1/10, senza data di ripristino (contenuti statici — disponibilità già corretta) — task schedulato 27/9', s:'2026-10-01', e:'2026-10-01', st:'up', ms:true},
      {t:'Gestionale — Fase 2 CRM ospiti: clienti.html LIVE (storico da reservations + note/tag + clienti manuali)', s:'2026-09-01', st:'done', ms:true},
      {t:'CRM: dati per newsletter/marketing (colonna consenso, filtro, export CSV) + verifica reale iscrizione Brevo', s:'2026-09-01', st:'done', ms:true},
      {t:'CRM integrato nel gestionale prenotazioni: badge cliente abituale + modifica prenotazione + link anagrafica', s:'2026-09-01', st:'done', ms:true},
      {t:'Anagrafica cliente: ora overlay diretto SOPRA il gestionale (non più tab/pagina separata) — fix richiesto 2 volte', s:'2026-09-01', st:'done', ms:true},
      {t:'Gestionale — Fase 4 statistiche (on-demand, scope da definire, no piano sala)', s:'2026-09-01', e:'2026-12-31', st:'future'},
      {t:'Fase 2 carta-garanzia (automazione, on-demand) → SUPERSEDED dal wizard /prenota.html', s:'2026-07-15', e:'2026-07-23', st:'done'},
      {t:'Merge SantaCantina dentro SafeTable a livello DB (schema unico) per liberare uno slot progetto free Supabase e riattivare NoShowApp (oggi in pausa)', s:'2026-09-16', e:'2026-09-16', st:'done'},
      {t:'Rubrica professionisti: tabella tornata locale su ST (ricreata, separata da NoShowApp) + pulsante import una tantum da NSA', s:'2026-09-01', st:'done', ms:true},
      {t:'menu-admin: riordino barra pulsanti in 3 tab con colori (Gestione menù e sito · Prenotazioni e voucher · Setup)', s:'2026-09-02', st:'done', ms:true},
      {t:'menu-admin: spostati in Setup — Reminder prenotazioni (tutto) + Garanzia penale/disdetta+Testi mail (da "Prenotazioni online") + importi buoni/reset contatore (da "Voucher — Gestione")', s:'2026-09-02', st:'done', ms:true},
      {t:'menu-admin: Preview/Traduci e Pubblica/🔑 spostati dalla top-bar (fissa su ogni tab) a sotto "Gestione menù e sito" (unico gruppo dove hanno senso)', s:'2026-09-02', st:'done', ms:true},
      {t:'Mail di ringraziamento post-visita: cliente prenotato dal sito e segnato "Arrivato" (mai manuali/no-show/cancellati), invio schedulato il giorno dopo alle 11:00 via job pg_cron, testo configurabile in menu-admin → Setup — invio spento di default, da riaccendere dopo revisione testi', s:'2026-09-02', st:'done', ms:true},
      {t:'Badge "mail di ringraziamento inviata/in coda" nella vista giorno, ricerca e scheda anagrafica del gestionale (richiesta Andrea: "come faccio a sapere se è stata inviata?")', s:'2026-09-02', st:'done', ms:true},
      {t:'CRM — 4 funzionalità dopo ricerca su SevenRooms/OpenTable/Resy/Brevo: compleanno/anniversario + pannello "Prossime ricorrenze", filtro "non viene da 3+/6+/12+ mesi", badge milestone Abituale/Fedelissimo, mini-dashboard KPI in clienti.html', s:'2026-09-02', st:'done', ms:true},
      {t:'Fix menu-admin: cambio tab ora pulisce il contenuto sotto (carta caricata ecc.) + "Procedure di aggiornamento" visibile solo su Gestione menù e sito', s:'2026-09-02', st:'done', ms:true},
      {t:'Gestionale Cantina — nuovo progetto Supabase "SantaCantina", 578 articoli migrati da Access', s:'2026-08-15', st:'done', ms:true},
      {t:'Gestionale Cantina — 3 Edge Function (catalogo/anagrafiche/magazzino) + cantina.html + carta vini dinamica', s:'2026-08-15', st:'done', ms:true},
      {t:'Gestionale Cantina — 50 cantine mancanti collegate + carta vini riga-unica formato PDF + setup categorie in carta', s:'2026-08-15', st:'done', ms:true},
      {t:'Gestionale Cantina — fix 92 descrizioni duplicate + logica zona/regione (Altre regioni) + gap dati Liguria', s:'2026-08-15', st:'done', ms:true},
      {t:'Gestionale Cantina — icone bottiglia/calice + regione sottolineata + ordine Altre regioni + titoli ingranditi', s:'2026-08-15', st:'done', ms:true},
      {t:'Gestionale Cantina — Denominazione/Zona diventano anagrafiche vere (tabelle collegate); Regione articolo derivata automaticamente dal produttore (sola lettura)', s:'2026-08-22', st:'done', ms:true},
      {t:'Gestionale Cantina — campo Ubicazione eliminato dal DB (mai usato); colonna Annata in Catalogo', s:'2026-08-22', st:'done'},
      {t:'Gestionale Cantina — carta vini: rifinitura tipografica di stampa (font/dimensioni titoli e numeri, margini @page 1,8cm sx, blocco annate non separabile, ordinamento alfabetico senza virgolette) + pulsante Stampa', s:'2026-08-22', e:'2026-08-25', st:'done', ms:true},
      {t:'Gestionale Cantina — riconciliazione prezzi con PDF ufficiale carta vini: 1 correzione (Erbaspada), 3 vini nascosti riattivati, 3 vini mancanti aggiunti (nascosti, in revisione)', s:'2026-08-25', st:'done', ms:true},
      {t:'Gestionale Cantina — commit cantina.html + menu-admin.html, primo giro d’uso reale', s:'2026-08-15', e:'2026-08-31', st:'done'},
      {t:'Fix mobile overflow orizzontale (menu-allergeni · cookies · privacy) — stesso pattern fix template 10/6, tabelle scorrevoli invece di sbordare', s:'2026-08-23', st:'done', ms:true},
      {t:'Food Cost giornaliero — tool costruito in menu-admin (date-range, dashboard Chart.js, sezione Beverage speculare, 4 KPI dedicate)', s:'2026-09-11', e:'2026-09-13', st:'done', ms:true},
      {t:'Food Cost — redesign inventario da range Dal/Al a conteggio puntuale per data (fc_inventario_conteggi), niente più doppia digitazione tra periodi consecutivi', s:'2026-09-13', st:'done', ms:true},
      {t:'Food Cost — badge "periodo non chiuso" sui KPI + storico conteggi con heatmap mensile + pannello periodi chiusi + auto-load ultimo periodo in Dashboard', s:'2026-09-13', st:'done', ms:true},
      {t:'Food Cost — riordino tab (Dashboard·Spese·Incassi·Vendite·Inventario·Costo piatti·Reparti) con colori per gruppo', s:'2026-09-13', st:'done'},
      {t:'Gantt trasversale ricostruito da zero + pubblicato su santamonicagenova.it/gantt (gantt.html noindex + gantt-data.js)', s:'2026-09-21', st:'done', ms:true},
      {t:'Food Cost — opzione futura (non richiesta come lavoro): Labor Cost % · Prime Cost % · Break-Even Point, serve una fonte dati costo-personale non ancora esistente', s:'2026-09-13', e:'2027-05-01', st:'future'},
      {t:'Aggiornare orari su Google Business Profile e schede esterne (settembre-ottobre)', s:'2026-08-28', e:'2026-09-25', st:'done'},
      {t:'Verificare dal vivo i flussi Food Cost (Tracciabilità, import Excel, IVA)', s:'2026-09-21', st:'future'},
      {t:'Restyling tema scuro del sito (home, menu, prenota, regala, dove-siamo)', s:'2026-09-04', e:'2026-09-04', st:'done'},
      {t:'Home — sezione Info a 3 card + newsletter restyle, FAQ multilingua, redesign regala.html', s:'2026-09-05', e:'2026-09-06', st:'done'},
      {t:'Modulo Food Cost in menu-admin (dashboard, KPI, Tracciabilità, Incassi, Inventario)', s:'2026-09-11', e:'2026-09-21', st:'done'},
      {t:'Pannello admin "Orari di Apertura" centralizzato + FAQ/JSON-LD/foglio orario allineati ai periodi', s:'2026-09-12', e:'2026-09-12', st:'done'},
      {t:'Rubrica professionisti — sincro a due vie con NoShowApp', s:'2026-09-18', e:'2026-09-18', st:'done'},
      {t:'Gestionale Cantina — carta Vini e carta Fine Pasto (categorie, stampa, icone)', s:'2026-09-19', e:'2026-09-20', st:'done'},
      {t:'Banner chiusura per vacanza 21-28 settembre', s:'2026-09-20', e:'2026-09-28', st:'done'},
    ]},
    { key:'seo', name:'SEO & GEO', badge:'progetto-seo', tasks:[
      {t:'Migrazione Cloudflare + fix Schema @type', s:'2026-05-25', e:'2026-05-31', st:'done'},
      {t:'Audit GSC baseline (sess. 15)', s:'2026-05-31', st:'done'},
      {t:'Content strategy ramo F (sess. 17)', s:'2026-05-31', st:'done'},
      {t:'Report riconciliato + title/meta home (sess. 18)', s:'2026-06-04', st:'done'},
      {t:'Competitor + siloing + GEO playbook (sess. 19)', s:'2026-06-05', st:'done'},
      {t:'KPI + CWV + accessibilità (sess. 20)', s:'2026-06-07', st:'done'},
      {t:'Scheletri 3 pillar + redirect /cucina (sess. 21)', s:'2026-06-08', st:'done'},
      {t:'Crawler AI/GEO + off-page + Bing (sess. 22)', s:'2026-06-10', st:'done'},
      {t:'Meta description + GBP + GEO baseline (sess. 23–24)', s:'2026-06-10', e:'2026-06-11', st:'done'},
      {t:'FAQ home + schema FAQPage (sess. 25)', s:'2026-06-11', st:'done', ms:true},
      {t:'GEO giro 2 + fix orari crawler-safe (sess. 25)', s:'2026-06-11', st:'done'},
      {t:'G9 Nicolò Lazzaroni rinforzato (index.html v2026.06.12.01)', s:'2026-06-12', st:'done', ms:true},
      {t:'AZIONE #2 orari schede terze (TheFork non gestibile; resto = affidamento ricrawl)', s:'2026-06-12', e:'2026-06-24', st:'done'},
      {t:'GEO giro 3 (ChatGPT + Claude 5° motore) ✅', s:'2026-06-13', st:'done', ms:true},
      {t:'GEO giro 4 (orari estivi: solo Gemini ok; ChatGPT/Claude al ricrawl)', s:'2026-06-24', st:'done', ms:true},
      {t:'GEO giro 5 (verifica ricrawl orari ChatGPT/Claude)', s:'2026-07-08', e:'2026-07-15', st:'future'},
      {t:'AEO impostato (lente dentro GEO) + audit skill seo-geo-aeo (AEO 7→8)', s:'2026-06-24', st:'done', ms:true},
      {t:'Quick-win AEO home LIVE (definizione + H1 + 6 heading-domanda + 3 liste)', s:'2026-06-24', st:'done'},
      {t:'P3 quick-win AEO (3 vendor) + deploy bucket A LIVE (no "gourmet", H1 entità, meta ~140c)', s:'2026-06-29', st:'done', ms:true},
      {t:'Revisione critica SEO/GEO/AEO + soft-404 CHIUSO (404.html LIVE) + rettifica DEPLOY doc', s:'2026-07-02', e:'2026-07-05', st:'done'},
      {t:'IndexNow/Crawler Hints Cloudflare attivato', s:'2026-07-03', st:'done', ms:true},
      {t:'Pretty URLs (email GSC): sitemap URL pulite + robots senza estensione LIVE — pending reinvio sitemap GSC', s:'2026-07-03', e:'2026-07-05', st:'done', ms:true},
      {t:'Canonical → URL pulite (debito pretty URLs, tocca template admin — col pacchetto pillar)', s:'2026-07-10', e:'2026-09-25', st:'done'},
      {t:'Intervista pillar: §1-4 raccolte (identità · materia prima · sostenibilità · stile) — in attesa §5 piatti firma', s:'2026-07-05', st:'up'},
      {t:'Piano recensioni (4,3★→4,6, leva GEO) + tentativo recupero TheFork Manager', s:'2026-07-10', e:'2026-08-31', st:'future'},
      {t:'Embriaco #8 profilato + backlink Vivarelli/I Cuochi chiusi (no dominio)', s:'2026-06-24', st:'done'},
      {t:'Backlink competitor Etra/Coco/Xena (avanti; dietro solo ai 2 stellati)', s:'2026-06-19', st:'done'},
      {t:'PR decennale comunicato — ABBANDONATO (decisione Andrea 24/6)', s:'2026-06-19', e:'2026-06-24', st:'done'},
      {t:'Brief SEO pillar /cucina-di-pesce (spec pronta)', s:'2026-06-19', st:'done', ms:true},
      {t:'Pillar #1 /cucina-di-pesce (blocco: brief Nicolò + foto; al go-live: bucket B title + FAQ fine dining)', s:'2026-06-15', e:'2026-07-31', st:'up'},
      {t:'Pillar #2 /sul-mare-lungomare', s:'2026-07-01', e:'2026-07-31', st:'future'},
      {t:'Pillar #3 /storia-santamonica', s:'2026-08-01', e:'2026-08-31', st:'future'},
      {t:'Content seriale IG + Brevo (2/mese)', s:'2026-06-15', e:'2026-11-30', st:'future'},
      {t:'Multilingua URL separate /en/ /fr/ (mini-progetto ≈3-4 sess, post-pillar)', s:'2026-09-01', e:'2026-10-31', st:'future'},
      {t:'Brevo automazioni email', s:'2026-08-01', e:'2026-09-25', st:'done'},
    ]},
    { key:'mkt', name:'Marketing & Awareness', badge:'progetto-marketing', tasks:[
      {t:'Apertura IG + strategia content', s:'2026-05-28', st:'done'},
      {t:'Setup IG operativo', s:'2026-05-28', e:'2026-06-05', st:'done'},
      {t:'Pubblici Meta P1/P2/P4 ricostruiti', s:'2026-05-26', e:'2026-06-02', st:'done'},
      {t:'Primo boost gambero P1', s:'2026-05-30', e:'2026-06-06', st:'done'},
      {t:'Audit infrastruttura Meta + 2FA', s:'2026-06-01', st:'done'},
      {t:'Strategia IG generale + asse Nord', s:'2026-06-10', st:'done'},
      {t:'Report IG settimanale automatico (GitHub Actions, PC-off)', s:'2026-06-15', st:'done', ms:true},
      {t:'Revisione segnali IG (condivisioni/watch time) + P3 + report aggiornato', s:'2026-06-16', st:'done', ms:true},
      {t:'Analisi insight teaser decennale (flyer 2.888 reach / 0 condiv.)', s:'2026-06-16', st:'done'},
      {t:'Sponsorizzata "Dieci anni": pivot a canale nativo "Metti in evidenza" (bypassa blocco #2859015 su 264), boost IN REVISIONE su post Monica', s:'2026-07-02', e:'2026-07-12', st:'done', ms:true},
      {t:'Post-mortem boost Reel decennale CHIUSO (56/60 ospiti, 10 pubblici, €13,88/prenotazione)', s:'2026-07-02', st:'done', ms:true},
      {t:'Riunione d’ufficio — punto della situazione Awareness (report interno, no gate)', s:'2026-07-12', st:'done', ms:true},
      {t:'Revisione Oppositiva IG generale — tentativo Zapier fallito (quota esaurita), pacchetto pronto per riprova', s:'2026-07-10', st:'done', ms:true},
      {t:'Brief esplorativo "pranzo leggero crudo" — terza via fine dining/casual, nessuna decisione presa', s:'2026-07-22', st:'done', ms:true},
      {t:'Nuova figura d’ufficio "Consulente Esterno Senior" (Metodo/Brand/Editoria/Vino/Turismo) + dossier consulenti reali verificati', s:'2026-08-23', st:'done', ms:true},
      {t:'Filone B — Turismo Gastronomico: brief consolidato Fase 4 (gate chiuso)', s:'2026-08-23', st:'done', ms:true},
      {t:'Filone B — Piano Awareness Fase 5 (3 formati: discorsivo/tabellare/timeline) — gate chiuso, P3 3 vendor esterni (8/9)', s:'2026-09-08', st:'done', ms:true},
      {t:'Filone B — Costruzione: concierge Melia + Palazzo Grillo (2° tentativo, modello Capitolo Riviera)', s:'2026-09-01', e:'2026-11-30', st:'up'},
      {t:'Filone B — rinnovo iscrizione Genova Gourmet (annuale, ferma da mesi)', s:'2026-09-01', e:'2026-10-31', st:'up'},
      {t:'Filone B — re-invio press kit + lista 15/22 a stampa/guide di viaggio enogastronomico nazionale', s:'2026-09-01', e:'2026-11-30', st:'future'},
      {t:'Filone B — contenuti sito "weekend gastronomico" (IT/EN/FR, sito già multilingua) + restyling foto GBP', s:'2026-09-15', e:'2026-11-30', st:'future'},
      {t:'Filone B — 4 settimane di raccolta baseline (provenienza booking, debito tecnico)', s:'2026-09-01', e:'2026-11-30', st:'future'},
      {t:'Baseline misurazione geografica IG (4 sett, post 2/7)', s:'2026-07-03', e:'2026-07-31', st:'future'},
      {t:'Gate Nord: decisione budget paid', s:'2026-08-01', st:'up', ms:true},
      {t:'Calendario cene a tema (entro ago)', s:'2026-07-01', e:'2026-08-31', st:'prog'},
      {t:'Mailing Brevo — lancio (entro 15 set)', s:'2026-08-15', e:'2026-09-15', st:'future'},
      {t:'Meta budget teaser (set, 300€)', s:'2026-09-01', e:'2026-09-30', st:'future'},
      {t:'Cene a tema «Mare d\'Inverno» (8 serate) — appiglio anche per Filone B turismo', s:'2026-09-01', e:'2027-04-30', st:'future'},
      {t:'Meta budget inverno — picco (700€)', s:'2026-11-01', e:'2027-04-30', st:'future'},
      {t:'Filone B — Transizione: prime serate Mare d’Inverno comunicate/misurate, decisione riserva adv Nord', s:'2026-12-01', e:'2027-02-28', st:'future'},
      {t:'★ Obiettivo +20% infrasettimanale (mis. nov–gen)', s:'2026-11-01', e:'2027-01-31', st:'future', ms:true},
      {t:'Filone B — Picco strategico: adv Nord Italia + push concierge/PR alta stagione (se leading positivi)', s:'2027-03-01', e:'2027-08-31', st:'future'},
      {t:'Sponsorizzata Salone Nautico', s:'2026-09-25', st:'prog'},
    ]},
    { key:'nsa', name:'NoShowApp (prodotto SaaS)', badge:'progetto-nsa', tasks:[
      {t:'NoShowApp fasi 1-5 completate (MVP no-show condiviso, accesso a invito, admin, UI + dominio, garanzia carta Stripe in test)', s:'2026-03-20', e:'2026-05-03', st:'done'},
      {t:'NoShowApp F6 — acquisire 10 beta tester (WhatsApp + demo dal vivo con carta test) e guida onboarding', s:'2026-10-01', st:'up'},
      {t:'NoShowApp F6 — registrare il marchio NoShowApp (verifica tmview.org, UIBM classe 42, ~200 €)', s:'2026-10-01', st:'up'},
      {t:'NoShowApp F6 — Stripe live mode + paywall abbonamento 29 €/mese (stop attivazione automatica beta) + notifica admin nuovi iscritti', s:'2026-11-01', e:'2026-12-31', st:'future'},
      {t:'NoShowApp: setup visibilità dati per-cliente (privato/condiviso, deciso da Andrea come titolare), possibile feature a pagamento', s:'2026-09-01', e:'2026-12-31', st:'future'},
      {t:'NoShowApp F6 — migrazione da GitHub Pages a Vercel (+ pagina carta custom Stripe Elements)', s:'2026-11-01', e:'2026-12-31', st:'future'},
      {t:'NoShowApp F6b — Stripe Connect Express: ogni ristoratore collega il proprio IBAN, addebiti diretti', s:'2027-01-01', e:'2027-03-31', st:'future'},
      {t:'NoShowApp F7 — landing pubblica per ristorante (noshowapp.it/prenota/nome) con garanzia carta', s:'2027-02-01', e:'2027-06-30', st:'future'},
      {t:'NoShowApp F8 — app native, caller ID, reminder Twilio, statistiche, TheFork/OpenTable, punteggio, FR/ES/DE (dopo 20+ utenti)', s:'2027-06-01', e:'2027-12-31', st:'future'},
    ]},
  ]
};
